---
# tasks file for ansible-role-barman
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: "install_{{ ansible_os_family }}.yml"
  tags: [barman, barman-install]

- include: configure.yml
  tags: [barman, barman-configure]

- include: cron.yml
  tags: [barman, barman-cron]
